# Generated by Django 4.1.1 on 2022-10-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_clientes_options'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Encabezado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gran Total')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('rel_cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.clientes', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('rel_factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facturas.factura_encabezado', verbose_name='Factura')),
                ('rel_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.productos', verbose_name='Producto')),
            ],
        ),
    ]
