# Generated by Django 4.1.1 on 2022-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_encabezado',
            name='fecha_factura',
            field=models.DateField(default='1900-01-01', verbose_name='Fecha'),
        ),
    ]
