# Generated by Django 4.1.1 on 2022-09-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('NI', 'NIT'), ('CC', 'Cedula de ciudadania'), ('PA', 'Pasaporte'), ('OT', 'Otro')], max_length=2, verbose_name='Tipo de documento')),
                ('num_documento', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
    ]
